Repository meetecho/janus-gateway, pull requests merged in 2022-08, with the labels that each got.

#3023 0.x: Fix media not enabled by subscribers on publisher renegotiations
  plugins/janus_videoroom.c
Labels: legacy

#3027 An optional id in the subscribe request to match a subscription with newly created elements in the stream list
  src/plugins/janus_videoroom.c
Labels: multistream

#3003 New way of capturing devices/tracks in janus.js
  .eslintrc.js
  html/audiobridgetest.js
  html/canvas.js
  html/devicetest.js
  html/e2etest.js
  html/echotest.js
  html/janus.js
  html/multiopus.js
  html/mvideoroomtest.js
  html/nosiptest.html
  html/nosiptest.js
  html/recordplaytest.js
  html/screensharingtest.js
  html/siptest.js
  html/streamingtest.js
  html/textroomtest.js
  html/videocalltest.js
  html/videoroomtest.js
  html/virtualbg.js
  html/voicemailtest.js
  html/vp9svctest.js
  html/webaudio.js
  src/mainpage.dox
Labels: please-test, multistream

#2998 Allow plugins to specify msid in SDPs
  conf/janus.plugin.streaming.jcfg.sample.in
  html/mvideoroomtest.js
  html/videoroomtest.js
  src/ice.c
  src/ice.h
  src/janus.c
  src/plugins/janus_streaming.c
  src/plugins/janus_videoroom.c
  src/sdp-utils.c
  src/sdp-utils.h
  src/sdp.c
Labels: multistream

#3014 New APIs for cascading VideoRoom publishers
  src/plugins/janus_videoroom.c
Labels: please-test, multistream
